### ISSUE TITLE
Fee

### ISSUE THREAD

**Issue by spammik** [mole3421278/Daibotuten-futures-trading-optimizer-bot#10]
Hello, how should I pay the fees? I mean...how would you know what I paid the fee, there is not any "code" or something.

Thanks.

**Comment by mole3421278** [comment]
Hello spammik,

the bot itself checks the transactions done in the last 30 days: if it sees that there is a transaction to one of the addresses listed in the section Devs Fee of the page https://github.com/mole3421278/Daibotuten-futures-trading-optimizer-bot with a sufficient amount (converted in usdt) to activate the bot, then it will start to work and it will generate a config file with three lines that must not be cancelled.
