### ISSUE TITLE
crypto still reliable?

### ISSUE THREAD

**Issue by justie2er** [mole3421278/Daibotuten-futures-trading-optimizer-bot#11]
Does it make sense to invest now in crypto?
Something still alive?

**Comment by mole3421278** [comment]
The crash seems to have halted. In the case of another one coming, use stop loss barriers and the expert mode to specify the price ranges on which you want to buy/sell.
It is also in development a new feature to stop/resume the trading depending on the twitter sentiment. Coming soon.

**Comment by mole3421278** [comment]
If nobody wants to add something else, going to close this issue.
